# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muxy < Formula
  desc "Proxy for simulating real-world distributed system failures to improve resilience in your applications."
  homepage "https://github.com/asjdf/muxy"
  version "1.0.2"
  license "MIT"

  on_macos do
    url "https://github.com/asjdf/muxy/releases/download/v1.0.2/muxy_Darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "5ee57d0cda857ef47c679cca2776e096d3684293263dfc3744b658c84330739e"

    def install
      bin.install "muxy"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asjdf/muxy/releases/download/v1.0.2/muxy_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "dc3a9d976165a6b51b12e85b253f42adccc42c21bc5eb2894d92c397e6b12484"

      def install
        bin.install "muxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/asjdf/muxy/releases/download/v1.0.2/muxy_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f8f84900200457aa31936a312d36d19fb9feb8132d21e85e3e9df9780bffc697"

      def install
        bin.install "muxy"
      end
    end
  end

  def caveats
    <<~EOS
      Check https://github.com/asjdf/muxy
    EOS
  end
end
